import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kudos App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col bg-black`}>
        <header className="bg-black text-white py-4">
          <div className="max-w-screen-lg mx-auto">
            <h1 className='text-2xl font-semibold'>Kudos App</h1>
          </div>
        </header>
        <main className='flex-1 flex bg-slate-200'>
          {children}
        </main>
        <footer className='bg-black text-center text-white flex min-h-[100px] items-center'>
          <div className='max-w-screen-lg mx-auto'>
            A Future Design Works App
          </div>
        </footer>
      </body>
    </html>
  )
}
